name: clean_flutter_login_app
description: A Stunding case of clean arc and TDD in a flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mocktail: ^0.3.0
  faker: ^2.1.0
  http: ^0.13.5
  flutter_launcher_icons: ^0.12.0
  equatable: ^2.0.5
  get: ^4.6.5
  flutter_secure_storage: ^8.0.0
  carousel_slider: ^4.2.1
  intl: ^0.18.0
  localstorage: ^4.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path_android: assets/CleanArchitecture.jpeg
  image_path_ios: assets/CleanArchitecture.jpeg